---
apt_packages:
  - git
  - curl
  - python3
  - python3-pip
  - ffmpeg
  - fzf
  - gpg
  - htop
  - jq
  - neovim
  - tmux
  - tree
  - watchman
  - wget
  - youtube-dl
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - libssl-dev
  - libsqlite3-dev
  - sqlite
  - imagemagick
  - unzip
