---
asdf_version: 0.10.2

asdf_plugins:
  - nodejs
  - ruby
  - golang
  - deno
  - java

nodejs_version: 18.12.1
yarn_version: 3.2.4
ruby_version: 3.1.2
golang_version: 1.19.3
deno_version: 1.27.2
java_version: openjdk-18

python_packages:
 - pynvim
 - docker-compose

gems:
  - bundler
  - neovim
  - rails
  - rubocop

node_modules:
  - yarn
  - neovim
  - expo-cli
  - prettier
