---
- name: Add an Apt repository for NeoVim
  become: yes
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    update_cache: yes
  tags:
    - packages

- name: Install the NeoVim package
  become: yes
  apt:
    name: neovim
    state: latest
    update_cache: yes
  tags:
    - packages

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.config/nvim/autoload/plug.vim"
  tags:
    - vim

- name: Install plugins
  command: nvim +PlugInstall +qall
  tags:
    - vim

