---
- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.config/nvim/autoload/plug.vim"
  tags:
    - vim

- name: Install plugins
  command: nvim +PlugInstall +qall
  tags:
    - vim

