---
- hosts: all
  vars_files:
    - vars/global.yml
    - vars/ubuntu.yml
    - vars/apt-packages.yml
    - vars/runtimes.yml

  tasks:
    - name: Install apt pacakges
      include_tasks: tasks/apt.task.yml

    - name: Install Doker
      include_tasks: tasks/docker.task.yml

    - name: Install asdf and progamming environments
      include_tasks: tasks/asdf.task.yml

    - name: Install programming modules
      include_tasks: tasks/modules.task.yml

    - name: Symlink dotfiles
      include_tasks: tasks/symlinks.task.yml

    - name: Install vim plugins
      include_tasks: tasks/vim.task.yml
